/// Flutter icons HomeScreenIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeScreenIcons
///      fonts:
///       - asset: fonts/HomeScreenIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeScreenIcons {
  HomeScreenIcons._();

  static const _kFontFam = 'HomeScreenIcons';
  static const String? _kFontPkg = null;

  static const IconData cardmenu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
